FROM node:22.17-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source code
COPY . .

RUN npm i

ARG PORT
ENV PORT=$PORT

# Start the application
CMD ["npm", "run", "dev", "--port", "$PORT"]
