version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: simple-api-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: simple-api
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - simple-api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-api-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/simple-api?authSource=admin
    depends_on:
      - mongodb
    networks:
      - simple-api-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  simple-api-network:
    driver: bridge
