FROM node:22.17-alpine

ARG PORT
ARG VITE_API_BASE_API_URL
ARG VITE_SOCKET_BASE_URL
ENV VITE_API_BASE_API_URL=$VITE_API_BASE_API_URL
ENV VITE_SOCKET_BASE_URL=$VITE_SOCKET_BASE_URL
ENV PORT=$PORT

# Set working directory
WORKDIR /app

# Expose port
EXPOSE $PORT

RUN yarn install

CMD  sh -c 'yarn install && yarn dev --port $PORT --host 0.0.0.0'


